<template>
	<h1 class="companyBranding">
		<span class="companyLogo" v-html="properties.companyLogo"></span>
		<span class="companyName">{{ properties.companyName }}</span>
	</h1>
	<button class="sidebarToggleBtn" @click="$emit('toggle-sidebar-display', true)">Hide sidebar</button>
	<ul class="optionsTree">
		<li :class="getOptionClass(1, option)" v-for="option in properties.options" :key="option.uniqueID">
			<router-link :to="option.route">
				<span class="optionLabel">{{ $t(["sidebars", properties.name, option.uniqueID].join(".")) }}</span>
			</router-link>
			<ol v-if="option.children.length > 0">
				<li :class="getOptionClass(2, childOption)" v-for="(childOption, index) in option.children" :key="childOption.uniqueID">
					<router-link :to="childOption.route">
						<span class="optionBulletPoint">{{childOption.isPassed ? "&#10003;" : index + 1 }}</span>
						<span class="optionLabel">{{ $t(["sidebars", properties.name, childOption.uniqueID].join(".")) }}</span>
					</router-link>
				</li>
			</ol>
		</li>
	</ul>
</template>

<script>
/**
* The component renders aside HTML element to use as a sidebar in the application. Its structure is generated by a config object, passed as props.
*
* @component Sidebar
* @author bivanov
*/
export default {
	name: "Sidebar",
	emits: ['toggleSidebarDisplay'],
	props: {
		properties: Object
	},
	setup (props) {
		
		/**
		* Returns class names for for the sidebar entries, depending on their indent level and status.
		*
		* @method getLayoutClass
		* @param {String} 			level			level of indent
		* @param {Object} 			option		config object
		* @returns {String}		 						class names
		* @author bivanov
		*/
		const getOptionClass = (level, option) => {
			let cls = ["level" + level + "Option"];
			if (option.isSelected) {
				cls.push("current");
			}
			if (option.isPassed) {
				cls.push("passed");
			}
			return cls.join(" ");
		};

		return {
			getOptionClass
		};
	}
}
</script>